name: Deploy Spring Boot to GCP VM

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Java Temurin 17 설정
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build project
        run: ./gradlew build

      - name: Copy JAR to GCP VM
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          HONEY_JAR: ${{ secrets.HONEY_JAR }}
          
      - name: Copy JAR to GCP VM
        run: |
          echo "${SSH_KEY}" > id_rsa
          chmod 600 id_rsa
          scp -v -o StrictHostKeyChecking=no -i id_rsa build/libs/${HONEY_JAR}.jar ${USERNAME}@${HOST}:/home/${USERNAME}/app.jar


      - name: Run the application on GCP VM
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "${SSH_KEY}" > id_rsa
          chmod 600 id_rsa
          ssh -o StrictHostKeyChecking=no -i id_rsa ${USERNAME}@${HOST} 'nohup java -jar /home/${USERNAME}/app.jar > /dev/null 2>&1 &'
